name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ${{vars.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: Build the Spring Boot Application Docker image
      run: |
        docker build ./ProductServiceDockerDummy --file ProductServiceDockerDummy/Dockerfile --tag rishabhgupta130/adv-springboot-api-repo:latest
        docker push rishabhgupta130/adv-springboot-api-repo
    - name: Build the Postgres Database Docker image
      run: |
        docker build ./Database Postgres --file Database Postgres/Dockerfile --tag rishabhgupta130/custompostgres-repo:latest
        docker push rishabhgupta130/custompostgres-repo
    - name: Build the Redis Cache Docker image
      run: |
        docker build ./Redis Cache --file Redis Cache/Dockerfile --tag rishabhgupta130/customredis-repo:latest
        docker push rishabhgupta130/customredis-repo
